"""
STEMPath — app.py
=================
Main Flask application for the STEMPath career pathway platform.

STEMPath helps Caribbean STEM students identify skill gaps between their
current academic profile and a target career role, then generates a
personalised learning pathway using Dijkstra's shortest-path algorithm.

Architecture:
    - Firebase Auth  : handles user authentication (client-side)
    - Flask session  : persists user state server-side
    - Dijkstra graph : built from data.py at startup; used to find
                       optimal learning paths through skill/resource nodes
    - Groq LLM       : generates personalised skill survey questions
    - YouTube API    : fetches embedded video resources per skill gap
    - O*NET roles    : loaded from data/roles.json (generated by import_onet_roles.py)
"""

from dotenv import load_dotenv
load_dotenv()
from flask import Flask, render_template, request, redirect, url_for, session, jsonify, abort
from functools import wraps
import os
import re
import pdfplumber
from docx import Document
import json
from pathlib import Path
from groq import Groq
from graph_builder import build_learning_graph
from pathfinder import find_learning_path
from data import courses
from stempath_db import (
    get_latest_profile,
    get_profile,
    get_progress,
    get_user_profiles,
    init_db,
    save_profile,
    save_progress,
    upsert_user,
)
import urllib.request
import urllib.parse

# Build the Dijkstra skill/resource graph once at startup so it is
# shared across all requests without being rebuilt on every call.
graph = build_learning_graph(courses)

app = Flask(__name__)
app.config["SECRET_KEY"]              = "dev-secret-key-change-me"
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"
app.config["SESSION_COOKIE_SECURE"]   = False
init_db()


# ── Auth decorator ────────────────────────────────────────────

def login_required(f):
    """
    Route decorator that redirects unauthenticated users to the home page.

    Checks for 'user_id' in the Flask session, which is set by the
    /set-session endpoint after a successful Firebase login. Any route
    decorated with @login_required will redirect to '/' if the user
    is not logged in.

    Args:
        f (function): The Flask view function to protect.

    Returns:
        function: The wrapped view function with auth check applied.
    """
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get("user_id"):
            return redirect(url_for("home"))
        return f(*args, **kwargs)
    return decorated


# ── Broad skill taxonomy for resume parsing ───────────────────

BROAD_SKILL_TAXONOMY = {
    "Python": ["python", "jupyter", "anaconda"],
    "SQL": ["sql", "mysql", "postgresql", "postgres", "sqlite", "oracle database", "transact-sql"],
    "JavaScript": ["javascript", "js", "node", "node.js", "react", "angular", "vue", "typescript"],
    "Java": ["java", "spring"],
    "HTML": ["html", "html5"],
    "CSS": ["css", "css3", "sass", "bootstrap"],
    "Git": ["git", "github", "gitlab", "bitbucket", "version control"],
    "Data Visualization": ["tableau", "power bi", "matplotlib", "seaborn", "plotly", "data visualization", "dashboard"],
    "Machine Learning": ["machine learning", "scikit", "tensorflow", "pytorch", "neural network", "keras"],
    "Networking": ["networking", "network", "tcp/ip", "cisco", "protocols", "router", "switch"],
    "Linux": ["linux", "bash", "shell scripting", "unix"],
    "Security Basics": ["cybersecurity", "security", "encryption", "firewall", "splunk", "siem"],
    "Cloud": ["aws", "azure", "gcp", "google cloud", "cloud", "docker", "kubernetes"],
    "APIs": ["rest api", "restful api", "graphql", "api development", "postman"],
    "Problem-solving": ["data structures", "problem solving", "problem-solving"],
    "Communication": ["communication", "presentation", "report writing"],
    "MATLAB": ["matlab"],
    "Excel": ["microsoft excel", "excel", "spreadsheet"],
    "Research": ["academic research", "research methods", "research", "labview"],
    "Statistics": ["statistics", "statistical analysis", "spss", "sas", "rstudio"],
}


# ── Resume parsing ────────────────────────────────────────────

def extract_text_from_pdf(path):
    """
    Extract plain text from all pages of a PDF file.

    Args:
        path (str): Absolute path to the PDF file.

    Returns:
        str: Concatenated text content of all pages, separated by newlines.
    """
    text = []
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            text.append(page.extract_text() or "")
    return "\n".join(text)


def extract_text_from_docx(path):
    """
    Extract plain text from a Microsoft Word (.docx) document.

    Args:
        path (str): Absolute path to the .docx file.

    Returns:
        str: Concatenated text of all paragraphs, separated by newlines.
    """
    doc = Document(path)
    return "\n".join(p.text for p in doc.paragraphs)


def extract_skills_from_text(text, known_skills):
    """
    Identify STEM skills mentioned in a block of text using two-layer matching.

    Layer 1 — Direct match: checks whether any skill from known_skills
    appears as a whole word in the text.

    Layer 2 — Taxonomy match: checks BROAD_SKILL_TAXONOMY keyword lists
    to catch common aliases (e.g. 'matplotlib' → 'Data Visualization').

    Layer 3 — Noise filtering: removes skills that appear only once and
    are not surrounded by skills-related context words, reducing false
    positives from incidental mentions.

    Args:
        text (str): Raw text extracted from a resume or document.
        known_skills (list[str]): List of canonical skill names from roles.json.

    Returns:
        list[str]: Sorted list of identified skill names.
    """
    t = text.lower()
    found = set()
    for sk in known_skills:
        if re.search(r'\b' + re.escape(sk.lower()) + r'\b', t):
            found.add(sk)
    for skill_name, keywords in BROAD_SKILL_TAXONOMY.items():
        for kw in keywords:
            if re.search(r'\b' + re.escape(kw.lower()) + r'\b', t):
                found.add(skill_name)
                break
    weak = set()
    for skill in found:
        matches = list(re.finditer(r'\b' + re.escape(skill.lower()) + r'\b', t))
        if len(matches) == 1:
            position    = matches[0].start()
            surrounding = t[max(0, position-200):position+200]
            if not any(w in surrounding for w in ["skill", "technolog", "proficien", "experience", "language", "tool"]):
                weak.add(skill)
    found -= weak
    return sorted(found)


def parse_resume_for_skills(file_path, known_skills):
    """
    Parse a resume file (PDF or DOCX) and extract recognised STEM skills.

    Dispatches to the appropriate text extractor based on file extension,
    then passes the extracted text to extract_skills_from_text.

    Args:
        file_path (str): Absolute path to the uploaded resume file.
        known_skills (list[str]): Canonical skill names to match against.

    Returns:
        list[str]: Sorted list of skills found in the resume.
                   Returns an empty list for unsupported file types.
    """
    if file_path.lower().endswith(".pdf"):
        text = extract_text_from_pdf(file_path)
    elif file_path.lower().endswith(".docx"):
        text = extract_text_from_docx(file_path)
    else:
        return []
    found = extract_skills_from_text(text, known_skills)
    print("=== RESUME EXTRACTION ===")
    print("Text sample:", text[:300])
    print("Skills found:", found)
    return found


# ── Roles catalog helpers ─────────────────────────────────────

BASE_DIR   = Path(__file__).parent
DATA_DIR   = BASE_DIR / "data"
ROLES_PATH = DATA_DIR / "roles.json"


def load_roles():
    """
    Load and validate the O*NET-derived roles catalog from roles.json.

    The roles.json file is generated by import_onet_roles.py from raw
    O*NET data files. Each role must contain: id, title, category,
    description, and top_skills (as a list).

    Returns:
        list[dict]: List of validated role dictionaries.

    Raises:
        FileNotFoundError: If roles.json does not exist at DATA_DIR.
        ValueError: If any role is missing required keys or has an
                    invalid top_skills type.
    """
    if not ROLES_PATH.exists():
        raise FileNotFoundError(f"Could not find roles catalog at: {ROLES_PATH}")
    with open(ROLES_PATH, "r", encoding="utf-8") as f:
        roles = json.load(f)
    required_keys = {"id", "title", "category", "description", "top_skills"}
    for r in roles:
        missing = required_keys - set(r.keys())
        if missing:
            raise ValueError(f"Role '{r.get('id','UNKNOWN')}' missing keys: {missing}")
        if not isinstance(r["top_skills"], list):
            raise ValueError(f"Role '{r['id']}' top_skills must be a list")
    return roles


def find_role_by_id(role_id, roles):
    """
    Find a single role dict by its unique string ID.

    Args:
        role_id (str): The slugified role identifier (e.g. 'data_scientist').
        roles (list[dict]): The full roles catalog returned by load_roles().

    Returns:
        dict | None: The matching role dict, or None if not found.
    """
    return next((r for r in roles if r["id"] == role_id), None)


def normalize_skill(s):
    """
    Normalise a skill name for case-insensitive comparison.

    Args:
        s (str): Raw skill name string.

    Returns:
        str: Lowercase, stripped skill name.
    """
    return s.strip().lower()


def get_graph_skills():
    """
    Return the set of all skill names present in the Dijkstra graph.

    Collects all values from the 'teaches' and 'prerequisites' fields
    across every course/resource node in data.py. Used to determine
    which missing skills are pathfindable via Dijkstra vs unsupported.

    Returns:
        set[str]: All skill node names in the graph, excluding 'ROOT'.
    """
    supported = set()
    for c in courses:
        supported.update(c.get("teaches", []))
        supported.update(c.get("prerequisites", []))
    supported.discard("ROOT")
    return supported


def score_skill_gaps(missing_skills, all_roles):
    """
    Score each missing skill by its frequency across the entire roles catalog.

    Skills that appear in more roles have higher market demand and receive
    a higher market_score. This helps prioritise which gaps the user should
    address first.

    Scoring:
        market_score = (role_frequency / total_roles) * 100
        priority     = High (>=60%), Medium (>=30%), Low (<30%)

    Args:
        missing_skills (list[str]): Skills the user is missing for their target role.
        all_roles (list[dict]): Full roles catalog used to compute frequencies.

    Returns:
        list[dict]: List of scored skill dicts sorted by market_score descending.
                    Each dict contains: skill, market_score, priority.
    """
    frequency = {}
    for role in all_roles:
        for skill in role.get("top_skills", []):
            key = normalize_skill(skill)
            frequency[key] = frequency.get(key, 0) + 1
    total_roles = max(len(all_roles), 1)
    scored = []
    for skill in missing_skills:
        freq         = frequency.get(normalize_skill(skill), 0)
        market_score = round((freq / total_roles) * 100)
        priority     = "High" if market_score >= 60 else "Medium" if market_score >= 30 else "Low"
        scored.append({"skill": skill, "market_score": market_score, "priority": priority})
    return sorted(scored, key=lambda x: x["market_score"], reverse=True)


# ── YouTube helper ────────────────────────────────────────────

def fetch_youtube_videos(query, max_results=2):
    """
    Search YouTube Data API v3 and return video metadata.

    Requires the YOUTUBE_API_KEY environment variable to be set.
    Returns an empty list silently if the key is missing or the
    API call fails, so the rest of the results page still renders.

    Args:
        query (str): Search query string (e.g. 'Python for beginners').
        max_results (int): Maximum number of videos to return (default 2).

    Returns:
        list[dict]: List of video dicts, each containing:
                    title, url, thumbnail, video_id.
                    Returns [] if API key is absent or request fails.
    """
    api_key = os.environ.get("YOUTUBE_API_KEY", "")
    if not api_key:
        return []
    try:
        import urllib.parse
        q   = urllib.parse.quote(query)
        url = (
            f"https://www.googleapis.com/youtube/v3/search"
            f"?part=snippet&q={q}&type=video&maxResults={max_results}"
            f"&relevanceLanguage=en&key={api_key}"
        )
        with urllib.request.urlopen(url, timeout=5) as r:
            data = json.loads(r.read().decode())
        videos = []
        for item in data.get("items", []):
            vid_id = item["id"]["videoId"]
            title  = item["snippet"]["title"]
            thumb  = item["snippet"]["thumbnails"]["medium"]["url"]
            videos.append({
                "title":     title,
                "url":       f"https://www.youtube.com/watch?v={vid_id}",
                "thumbnail": thumb,
                "video_id":  vid_id,
                "embed_url": f"https://www.youtube.com/embed/{vid_id}",
            })
        return videos
    except Exception as e:
        print("YouTube API error:", e)
        return []


def microsoft_learn_search_url(query):
    return f"https://learn.microsoft.com/en-us/search/?terms={urllib.parse.quote(query)}"


def _question_for_skill(skill, reason):
    if reason == "validate_claimed":
        question = (
            f"You listed {skill}. How confident are you applying it in a "
            "coursework, project, or workplace task?"
        )
    else:
        question = (
            f"{skill} is important for this career path. How much experience "
            "do you currently have with it?"
        )
    return {
        "skill": skill,
        "reason": reason,
        "question": question,
        "scale_labels": {
            "1": "No experience",
            "3": "Some experience",
            "5": "Proficient",
        },
    }


def build_dynamic_survey_questions(profile_data, role):
    role_skills = role.get("top_skills", []) if role else []
    claimed_skills = profile_data.get("skills", []) or []
    claimed_norm = {normalize_skill(s) for s in claimed_skills}

    claimed_target_skills = [
        skill for skill in role_skills
        if normalize_skill(skill) in claimed_norm
    ]
    missing_target_skills = [
        skill for skill in role_skills
        if normalize_skill(skill) not in claimed_norm
    ]

    # The count is data-driven: validate up to three claimed role skills,
    # then ask about the highest-priority gaps. This avoids a fixed survey size.
    validate_count = min(3, len(claimed_target_skills))
    gap_count = min(7 - validate_count, len(missing_target_skills))

    questions = [
        _question_for_skill(skill, "validate_claimed")
        for skill in claimed_target_skills[:validate_count]
    ]
    questions.extend(
        _question_for_skill(skill, "assess_gap")
        for skill in missing_target_skills[:gap_count]
    )

    rationale = {
        "claimed_target_count": len(claimed_target_skills),
        "missing_target_count": len(missing_target_skills),
        "validate_count": validate_count,
        "gap_count": gap_count,
        "total": len(questions),
    }
    return questions, rationale, missing_target_skills


def build_graph_overview(graph):
    skill_nodes = [
        n for n in graph.nodes
        if n != "ROOT" and not str(n).startswith("GATE::")
    ]
    gate_nodes = [n for n in graph.nodes if str(n).startswith("GATE::")]
    edges = []
    visual_edges = []
    visual_nodes = set()
    for source, target, data in graph.edges(data=True):
        course = data.get("course", "")
        if course == "return_to_root":
            continue
        visual_nodes.update([source, target])
        edges.append({
            "from": source,
            "to": target,
            "course": course,
            "time": data.get("time", 0),
            "difficulty": data.get("difficulty", 0),
            "cost": data.get("cost", 0),
            "is_gate_check": course.startswith("prereq_check::"),
        })
        visual_edges.append({
            "from": source,
            "to": target,
            "course": course,
            "is_gate_check": course.startswith("prereq_check::"),
        })

    prereq_targets = {edge["to"] for edge in visual_edges}
    levels = {"ROOT": 0}
    for node in visual_nodes:
        if node not in levels:
            levels[node] = 1 if node not in prereq_targets else 2

    changed = True
    while changed:
        changed = False
        for edge in visual_edges:
            source_level = levels.get(edge["from"], 1)
            target_level = levels.get(edge["to"], 1)
            next_level = min(source_level + 1, 5)
            if next_level > target_level:
                levels[edge["to"]] = next_level
                changed = True

    grouped = {}
    for node in visual_nodes:
        grouped.setdefault(levels.get(node, 1), []).append(node)

    graph_nodes = []
    for level in sorted(grouped):
        nodes = sorted(grouped[level])
        for index, node in enumerate(nodes):
            count = len(nodes)
            graph_nodes.append({
                "id": re.sub(r"[^a-zA-Z0-9_-]", "_", str(node)),
                "label": str(node).replace("GATE::", "Gate: "),
                "raw": node,
                "level": level,
                "x": 80 + (level * 165),
                "y": 70 + (index + 1) * (420 / (count + 1)),
                "type": (
                    "root" if node == "ROOT"
                    else "gate" if str(node).startswith("GATE::")
                    else "skill"
                ),
            })
    node_ids = {node["raw"]: node["id"] for node in graph_nodes}
    node_lookup = {node["raw"]: node for node in graph_nodes}
    graph_visual = {
        "nodes": graph_nodes,
        "layers": [
            {
                "level": level,
                "title": "Start" if level == 0 else f"Layer {level}",
                "nodes": [
                    {
                        "label": str(node).replace("GATE::", "Gate: "),
                        "raw": node,
                        "type": (
                            "root" if node == "ROOT"
                            else "gate" if str(node).startswith("GATE::")
                            else "skill"
                        ),
                    }
                    for node in sorted(grouped[level])
                ],
            }
            for level in sorted(grouped)
        ],
        "edges": [
            {
                **edge,
                "from_id": node_ids.get(edge["from"], ""),
                "to_id": node_ids.get(edge["to"], ""),
                "from_x": node_lookup.get(edge["from"], {}).get("x", 0),
                "from_y": node_lookup.get(edge["from"], {}).get("y", 0),
                "to_x": node_lookup.get(edge["to"], {}).get("x", 0),
                "to_y": node_lookup.get(edge["to"], {}).get("y", 0),
            }
            for edge in visual_edges
        ],
    }

    return {
        "node_count": graph.number_of_nodes(),
        "edge_count": graph.number_of_edges(),
        "skill_nodes": sorted(skill_nodes),
        "gate_nodes": sorted(gate_nodes),
        "edges": sorted(edges, key=lambda e: (str(e["from"]), str(e["to"]), str(e["course"]))),
        "visual": graph_visual,
        "cost_formula": "time x weight_time + difficulty x weight_difficulty + cost x weight_cost",
    }


# ── Build recommended learning ────────────────────────────────

def build_recommended_learning(learning_paths):
    """
    Convert raw Dijkstra learning paths into structured learning items
    suitable for display in the results template.

    For each learning path (one per skill gap), extracts the terminal
    course step and builds a human-readable learning item with a link,
    provider name, prerequisite chain, and total Dijkstra cost.

    Link priority: edX link > Microsoft Learn link > provider fallback.

    Args:
        learning_paths (list[dict]): Output of the Dijkstra pathfinding loop
            in the results route. Each dict contains: target_skill, path,
            steps, total_cost.

    Returns:
        list[dict]: List of learning item dicts for the results template,
                    each containing: skill, title, provider, format, link,
                    path, prereqs, total_cost.
    """
    items = []
    for lp in learning_paths:
        real_steps = [
            s for s in lp.get("steps", [])
            if s.get("course")
            and s["course"] != "return_to_root"
            and not s["course"].startswith("prereq_check::")
        ]
        if not real_steps:
            continue
        final_step     = real_steps[-1]
        learning_nodes = []
        for step in real_steps:
            to_node = step.get("to", "")
            if to_node and to_node != "ROOT" and not str(to_node).startswith("GATE::"):
                if not learning_nodes or learning_nodes[-1] != to_node:
                    learning_nodes.append(to_node)
        if not learning_nodes:
            continue
        prereqs   = learning_nodes[:-1] if len(learning_nodes) > 1 else []
        edx_link  = final_step.get("edx_link") or final_step.get("edx", "")
        ms_link   = final_step.get("ms_learn_search") or final_step.get("ms_learn") or final_step.get("microsoft", "")
        best_link = edx_link or ms_link or ""
        if edx_link:
            provider = final_step.get("provider") or "edX"
        elif ms_link:
            provider = "Microsoft Learn"
        else:
            provider = final_step.get("provider") or "edX / Coursera"
        items.append({
            "skill":      lp.get("target_skill", ""),
            "title":      final_step.get("course", ""),
            "provider":   provider,
            "format":     "Guided path",
            "link":       best_link,
            "path":       learning_nodes,
            "prereqs":    prereqs,
            "total_cost": round(lp.get("total_cost", 0), 1),
        })
    return items


# ── Cert library ──────────────────────────────────────────────

CERT_LIBRARY = [
    {"name": "Google Data Analytics Professional Certificate", "provider": "Coursera",
     "level": "Beginner–Intermediate", "skills": ["SQL", "Data Visualization", "Spreadsheets", "Data Analysis"],
     "tags": ["data", "analytics", "software", "technology"],
     "link": "https://www.coursera.org/professional-certificates/google-data-analytics"},
    {"name": "IBM Data Science Professional Certificate", "provider": "Coursera",
     "level": "Intermediate", "skills": ["Python", "Machine Learning", "Data Analysis", "SQL"],
     "tags": ["data", "software", "science", "technology"],
     "link": "https://www.coursera.org/professional-certificates/ibm-data-science"},
    {"name": "Microsoft Azure Fundamentals (AZ-900)", "provider": "Microsoft",
     "level": "Beginner", "skills": ["Cloud", "Networking", "Security Basics"],
     "tags": ["it", "security", "software", "technology"],
     "link": "https://learn.microsoft.com/en-us/certifications/azure-fundamentals/"},
    {"name": "CompTIA Security+", "provider": "CompTIA",
     "level": "Intermediate", "skills": ["Security Basics", "Networking", "Incident Response", "Linux"],
     "tags": ["security", "it", "technology"],
     "link": "https://www.comptia.org/certifications/security"},
    {"name": "AWS Certified Cloud Practitioner", "provider": "AWS",
     "level": "Beginner", "skills": ["Cloud", "Networking", "Security Basics"],
     "tags": ["it", "software", "technology"],
     "link": "https://aws.amazon.com/certification/certified-cloud-practitioner/"},
    {"name": "Google Project Management Certificate", "provider": "Coursera",
     "level": "Beginner–Intermediate", "skills": ["Project Management", "Communication", "Teamwork"],
     "tags": ["business", "software", "healthcare", "science", "engineering", "technology"],
     "link": "https://www.coursera.org/professional-certificates/google-project-management"},
    {"name": "Meta Front-End Developer Certificate", "provider": "Coursera / Meta",
     "level": "Beginner–Intermediate", "skills": ["JavaScript", "HTML", "CSS", "React", "APIs"],
     "tags": ["software", "it", "technology"],
     "link": "https://www.coursera.org/professional-certificates/meta-front-end-developer"},
    {"name": "Google IT Support Professional Certificate", "provider": "Coursera / Google",
     "level": "Beginner", "skills": ["Networking", "Linux", "Security Basics", "Cloud"],
     "tags": ["it", "security", "technology"],
     "link": "https://www.coursera.org/professional-certificates/google-it-support"},
    {"name": "AutoCAD Certified Professional", "provider": "Autodesk",
     "level": "Intermediate", "skills": ["AutoCAD", "Technical Drawing", "CAD"],
     "tags": ["engineering", "mechanical", "civil"],
     "link": "https://www.autodesk.com/certification/all-certifications/autocad"},
    {"name": "MATLAB Fundamentals", "provider": "MathWorks",
     "level": "Beginner–Intermediate", "skills": ["MATLAB", "Simulation", "Signal Processing", "Data Analysis"],
     "tags": ["engineering", "science", "physics", "mathematics"],
     "link": "https://www.mathworks.com/learn/training/matlab-fundamentals.html"},
    {"name": "Six Sigma Green Belt", "provider": "ASQ",
     "level": "Intermediate", "skills": ["Quality Control", "Statistical Analysis", "Process Improvement"],
     "tags": ["engineering", "mechanical", "industrial"],
     "link": "https://asq.org/cert/six-sigma-green-belt"},
    {"name": "PMP — Project Management Professional", "provider": "PMI",
     "level": "Advanced", "skills": ["Project Management", "Communication", "Risk Management", "Teamwork"],
     "tags": ["engineering", "software", "science", "business"],
     "link": "https://www.pmi.org/certifications/project-management-pmp"},
    {"name": "Medical Imaging Fundamentals (edX)", "provider": "edX",
     "level": "Intermediate", "skills": ["Medical Imaging", "Radiation Physics", "MATLAB", "Data Analysis"],
     "tags": ["healthcare", "physics", "science"],
     "link": "https://www.edx.org/learn/medical-imaging"},
    {"name": "Radiation Protection Supervisor Certificate", "provider": "IAEA / National Bodies",
     "level": "Intermediate", "skills": ["Radiation Safety", "Dosimetry", "Radiation Physics"],
     "tags": ["healthcare", "physics", "science"],
     "link": "https://www.iaea.org/resources/rpop/health-professionals/radiation-therapy/medical-physics"},
    {"name": "Google Health Data Analytics", "provider": "Coursera",
     "level": "Intermediate", "skills": ["Data Analysis", "Research", "Communication", "Excel"],
     "tags": ["healthcare", "science", "data"],
     "link": "https://www.coursera.org/learn/health-data-analytics"},
    {"name": "IBM Data Analyst Professional Certificate", "provider": "Coursera / IBM",
     "level": "Beginner–Intermediate", "skills": ["Python", "SQL", "Excel", "Data Visualization", "Research"],
     "tags": ["science", "data", "analytics"],
     "link": "https://www.coursera.org/professional-certificates/ibm-data-analyst"},
    {"name": "Research Methods and Statistics (Coursera)", "provider": "Coursera",
     "level": "Beginner–Intermediate", "skills": ["Research", "Statistical Analysis", "Data Analysis", "Communication"],
     "tags": ["science", "healthcare", "engineering"],
     "link": "https://www.coursera.org/learn/research-methods"},
]

# ── STEM category map for roles filter ───────────────────────
STEM_MAP = {
    "Science":     ["science", "life science", "physical science", "environmental science",
                    "medical physics", "physics", "chemistry", "biology"],
    "Technology":  ["technology", "it", "software", "computing", "data science",
                    "cybersecurity", "information technology", "computer science"],
    "Engineering": ["engineering", "civil engineering", "mechanical engineering",
                    "electrical engineering", "chemical engineering"],
    "Mathematics": ["mathematics", "math", "statistics", "actuarial"],
}


# ── Routes ────────────────────────────────────────────────────

@app.get("/")
def home():
    """Render the public landing page."""
    return render_template("home.html")


from werkzeug.utils import secure_filename
ALLOWED_RESUME_EXTS = {".pdf", ".docx"}


@app.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    """
    Display and process the user's academic profile form.

    GET:  Renders profile.html pre-filled with any existing session data.
    POST: Validates and saves the submitted profile (degree, location,
          skills, certifications, courses, optimize_for preference).
          Optionally parses an uploaded resume to extract additional skills.
          Redirects to /survey if a role is already selected, else /roles.

    Session keys written:
        profile       — dict of all profile fields
        flash         — success message shown on next page load
        resume_notice — feedback about resume parsing result
    """
    resume_notice = None
    if request.method == "POST":
        user_id            = session.get("user_id")
        degree             = request.form.get("degree", "").strip()
        major              = request.form.get("major", "").strip()
        location           = request.form.get("location", "").strip()
        gpa                = request.form.get("gpa", "").strip()
        certifications_raw = request.form.get("certifications", "").strip()
        courses_raw        = request.form.get("courses", "").strip()
        skills_raw         = request.form.get("skills", "").strip()

        user_skills  = [s.strip() for s in skills_raw.split(",")         if s.strip()]
        user_certs   = [c.strip() for c in certifications_raw.split(",") if c.strip()]
        user_courses = [c.strip() for c in courses_raw.split(",")        if c.strip()]
        resume_path  = None

        roles_data   = load_roles()
        known_skills = sorted({skill for r in roles_data for skill in r.get("top_skills", [])})

        resume_file = request.files.get("resume")
        if resume_file and resume_file.filename:
            safe_name = secure_filename(resume_file.filename)
            ext       = Path(safe_name).suffix.lower()
            if ext not in ALLOWED_RESUME_EXTS:
                resume_notice = "Resume upload ignored: please upload a PDF or DOCX file."
            else:
                uploads_dir = Path(__file__).parent / "uploads"
                uploads_dir.mkdir(exist_ok=True)
                save_path = uploads_dir / safe_name
                resume_file.save(str(save_path))
                resume_path = str(save_path)
                try:
                    resume_skills = parse_resume_for_skills(str(save_path), known_skills)
                    before        = len(set(user_skills))
                    user_skills   = sorted(set(user_skills) | set(resume_skills))
                    added         = max(0, len(set(user_skills)) - before)
                    resume_notice = (
                        f"Resume parsed — {added} skill(s) added." if added > 0
                        else "Resume parsed — no new skills found beyond what you entered."
                    )
                except Exception as e:
                    resume_notice = "Resume saved but we couldn't extract skills from it."
                    print("Resume parsing error:", e)

        profile_data = {
            "degree":         degree,
            "major":          major,
            "location":       location,
            "gpa":            gpa,
            "skills":         user_skills,
            "certifications": user_certs,
            "courses":        user_courses,
            "optimize_for":   request.form.get("optimize_for", "balanced"),
        }

        saved_profile = save_profile(
            user_id,
            profile_data,
            profile_id=session.get("active_profile_id"),
            resume_path=resume_path,
            create_new=session.pop("create_new_profile", False),
        )

        session["profile"] = saved_profile or profile_data
        if saved_profile:
            session["active_profile_id"] = saved_profile["id"]
        session["resume_notice"] = resume_notice
        session["flash"]         = "Profile saved successfully!"

        if session.get("selected_role_id"):
            return redirect(url_for("survey"))
        else:
            return redirect(url_for("roles"))

    existing = get_latest_profile(session.get("user_id")) or session.get("profile", {})
    if existing:
        session["profile"] = existing
        session["active_profile_id"] = existing.get("id")
    resume_notice = session.pop("resume_notice", None)
    return render_template("profile.html", profile=existing, resume_notice=resume_notice)


@app.get("/profile/new")
@login_required
def new_profile():
    session.pop("profile", None)
    session.pop("active_profile_id", None)
    session["create_new_profile"] = True
    return redirect(url_for("profile"))


@app.get("/profile/<int:profile_id>")
@login_required
def open_profile(profile_id):
    profile_data = get_profile(session.get("user_id"), profile_id)
    if not profile_data:
        abort(403)

    session["profile"] = profile_data
    session["active_profile_id"] = profile_data["id"]
    return redirect(url_for("profile"))


@app.route("/roles", methods=["GET"])
@login_required
def roles():
    """
    Display the browsable STEM roles catalog with search and STEM filtering.

    Supports two query parameters:
        q   (str): Free-text search matched against role title, description,
                   and top_skills.
        cat (str): STEM category filter — one of Science, Technology,
                   Engineering, Mathematics. Matched via STEM_MAP aliases
                   against the role's category field from roles.json.

    Returns the filtered list of roles to roles.html for display.
    """
    profile_data   = get_latest_profile(session.get("user_id")) or session.get("profile", {})
    if profile_data:
        session["profile"] = profile_data
        session["active_profile_id"] = profile_data.get("id")
    roles_catalog  = load_roles()
    query          = request.args.get("q", "").strip().lower()
    category       = request.args.get("cat", "").strip()
    categories     = sorted({r["category"] for r in roles_catalog})
    filtered_roles = []

    for r in roles_catalog:
        matches_query = (
            not query
            or query in r["title"].lower()
            or query in r["description"].lower()
            or any(query in sk.lower() for sk in r["top_skills"])
        )
        if not category:
            matches_cat = True
        else:
            role_cat_lower = r["category"].strip().lower()
            allowed_cats   = [c.lower() for c in STEM_MAP.get(category, [category.lower()])]
            matches_cat    = role_cat_lower in allowed_cats or any(
                alias in role_cat_lower for alias in allowed_cats
            )
        if matches_query and matches_cat:
            filtered_roles.append(r)

    return render_template(
        "roles.html",
        profile=profile_data,
        roles=filtered_roles,
        categories=categories,
        q=request.args.get("q", ""),
        cat=category,
    )


@app.post("/select-role")
def select_role():
    """
    Store the user's chosen role ID in the session and redirect to profile.

    Receives role_id from a hidden form field on the roles page.
    The selected role is used by the results route to compute skill gaps.

    Session keys written:
        selected_role_id — the slugified O*NET role identifier.
    """
    role_id = request.form.get("role_id", "").strip()
    if not role_id:
        return redirect(url_for("roles"))
    session["selected_role_id"] = role_id
    return redirect(url_for("profile"))


@app.get("/results")
@login_required
def results():
    """
    Compute and render the personalised career pathway and recommendations.

    This is the core route of STEMPath. It performs the following steps:

    1. Skill gap analysis:
       Compares the user's confirmed skills (from profile + completed progress)
       against the target role's top_skills from roles.json. Produces:
         - missing_skills     : skills the user needs to acquire
         - pathfindable_skills: missing skills present in the Dijkstra graph
         - unsupported_skills : missing skills not yet in the graph
         - match_score        : percentage of role skills already held

    2. Dijkstra pathfinding (O(V+E) log V):
       For each pathfindable skill gap, calls find_learning_path() with
       user-selected weight presets (time / cost / difficulty / balanced).
       Each path traverses video intro nodes → course nodes → certification
       nodes, producing an ordered sequence of learning resources.

    3. YouTube resource mapping:
       For each skill gap, fetches embedded videos by:
         a. Using youtube_query from video nodes in the Dijkstra path
         b. Always including a Khan Academy search
         c. Falling back to a generic search if fewer than 2 results

    4. Certification recommendations:
       Matches CERT_LIBRARY entries against the user's skill gaps and role
       category, returning up to 4 relevant certifications.

    5. Job listings:
       Attempts to fetch live Caribbean job listings via the CaribbeanJobs
       adapter; falls back to a direct search link if unavailable.

    Returns:
        Rendered results.html with a results_obj dict containing all
        computed data for the roadmap, resources, and recommendations.
    """
    print("=== RESULTS DEBUG ===")
    print("profile:", session.get("profile"))
    print("selected_role_id:", session.get("selected_role_id"))
    print("=====================")
    profile_data = get_latest_profile(session.get("user_id")) or session.get("profile")
    if profile_data:
        session["profile"] = profile_data
        session["active_profile_id"] = profile_data.get("id")
    selected_role_id = session.get("selected_role_id")

    if not profile_data:
        return redirect(url_for("profile"))
    if not selected_role_id:
        return redirect(url_for("roles"))

    roles_catalog = load_roles()
    role          = find_role_by_id(selected_role_id, roles_catalog)
    if not role:
        session.pop("selected_role_id", None)
        return redirect(url_for("roles"))

    # ── Skill gap ──────────────────────────────────────
    user_skills = list(profile_data.get("skills", []) or [])

    existing_progress = get_progress(
        session.get("user_id"),
        profile_id=session.get("active_profile_id"),
        role_id=selected_role_id,
    )
    completed_skills = existing_progress.get("completed", [])
    if completed_skills:
        existing_norm = {normalize_skill(s) for s in user_skills}
        for s in completed_skills:
            if normalize_skill(s) not in existing_norm:
                user_skills.append(s)

    user_skills_norm = {normalize_skill(s) for s in user_skills}
    role_top_skills  = role.get("top_skills", []) or []
    role_skills_norm = [normalize_skill(s) for s in role_top_skills]

    missing_skills = [
        role_top_skills[i]
        for i, sk in enumerate(role_skills_norm)
        if sk and sk not in user_skills_norm
    ]

    graph_skills        = get_graph_skills()
    pathfindable_skills = [s for s in missing_skills if s in graph_skills]
    unsupported_skills  = [s for s in missing_skills if s not in graph_skills]
    scored_gaps         = score_skill_gaps(missing_skills, roles_catalog)
    role_total          = max(len(role_top_skills), 1)
    have_count          = role_total - len(missing_skills)
    match_score         = int(round((have_count / role_total) * 100))

    # ── Certifications ─────────────────────────────────
    role_category_tag = (role.get("category", "") or "").strip().lower()
    missing_norm      = {normalize_skill(s) for s in missing_skills}
    recommended_certs = []
    for cert in CERT_LIBRARY:
        cert_skill_norm = {normalize_skill(s) for s in cert["skills"]}
        covers_gap      = bool(missing_norm.intersection(cert_skill_norm))
        category_match  = role_category_tag in [t.lower() for t in cert.get("tags", [])]
        if covers_gap or category_match:
            covered = list(missing_norm.intersection(cert_skill_norm))
            reason  = (
                f"Helps you build: {', '.join(covered[:3])}." if covered
                else f"Recommended for {role.get('category','')} roles."
            )
            recommended_certs.append({
                "name": cert["name"], "provider": cert["provider"],
                "level": cert["level"], "skills": cert["skills"],
                "reason": reason, "link": cert.get("link", ""),
            })
    recommended_certs = recommended_certs[:4]

    # ── Dijkstra paths ─────────────────────────────────
    from data import courses as course_catalog
    course_lookup  = {c["name"]: c for c in course_catalog}
    optimize_for   = profile_data.get("optimize_for", "balanced")
    weight_presets = {
        "time":     {"weight_time": 0.8, "weight_difficulty": 0.1, "weight_cost": 0.1},
        "cost":     {"weight_time": 0.1, "weight_difficulty": 0.1, "weight_cost": 0.8},
        "balanced": {"weight_time": 0.4, "weight_difficulty": 0.3, "weight_cost": 0.3},
        "easy":     {"weight_time": 0.1, "weight_difficulty": 0.8, "weight_cost": 0.1},
    }
    weights        = weight_presets.get(optimize_for, weight_presets["balanced"])
    learning_paths = []
    for gap_skill in pathfindable_skills[:4]:
        path, cost = find_learning_path(graph, user_skills, gap_skill, **weights)
        if path and len(path) > 1:
            steps       = []
            graph_edges = []
            for i in range(len(path) - 1):
                edge        = graph.get_edge_data(path[i], path[i + 1])
                course_name = edge.get("course", "")
                edge_cost   = (
                    edge.get("time", 0) * weights["weight_time"]
                    + edge.get("difficulty", 0) * weights["weight_difficulty"]
                    + edge.get("cost", 0) * weights["weight_cost"]
                )
                graph_edges.append({
                    "from":       path[i],
                    "to":         path[i + 1],
                    "course":     course_name,
                    "time":       edge.get("time", 0),
                    "difficulty": edge.get("difficulty", 0),
                    "cost":       edge.get("cost", 0),
                    "edge_cost":  round(edge_cost, 1),
                    "is_hidden":  course_name == "return_to_root" or course_name.startswith("prereq_check::"),
                })
                if course_name == "return_to_root" or course_name.startswith("prereq_check::"):
                    continue
                course_data = course_lookup.get(course_name, {})
                video_query = f"{path[i + 1]} {course_name} beginner tutorial"
                videos      = fetch_youtube_videos(video_query, max_results=3)
                learn_query = f"{path[i + 1]} {course_name}"
                steps.append({
                    "from":           path[i],
                    "to":             path[i + 1],
                    "course":         course_name,
                    "provider":       course_data.get("provider", ""),
                    "edx_link":       course_data.get("edx_link", ""),
                    "ms_learn":       microsoft_learn_search_url(learn_query),
                    "ms_learn_search": microsoft_learn_search_url(learn_query),
                    "youtube_search": course_data.get("youtube", ""),
                    "topics":         course_data.get("topics", []),
                    "video_query":    video_query,
                    "videos":         videos,
                    "time":           edge.get("time", 0),
                    "difficulty":     edge.get("difficulty", 0),
                    "cost":           edge.get("cost", 0),
                    "edge_cost":      round(edge_cost, 1),
                    "why_this_step":  (
                        f"This course moves you from {path[i]} to {path[i + 1]} "
                        f"and was selected because it is on the lowest-cost route "
                        f"to {gap_skill} under your {optimize_for} preference."
                    ),
                })
            learning_paths.append({
                "target_skill": gap_skill,
                "path":         path,
                "graph_edges":  graph_edges,
                "steps":        steps,
                "total_cost":   round(cost, 1),
                "weights":      weights,
                "optimize_for": optimize_for,
            })

    recommended_learning = build_recommended_learning(learning_paths)

    # ── YouTube videos mapped via resource graph ────────
    skill_videos = {}
    for gap in missing_skills[:6]:
        videos = []
        seen   = set()

        # Step 1: use youtube_query from video nodes in the Dijkstra path
        for lp in learning_paths:
            if lp.get("target_skill") != gap:
                continue
            for step in lp.get("steps", []):
                course_name = step.get("course", "")
                course_data = course_lookup.get(course_name, {})
                if course_data.get("resource_type") == "video":
                    query = course_data.get("youtube_query", f"{gap} tutorial")
                    for v in fetch_youtube_videos(query, max_results=1):
                        if v["video_id"] not in seen:
                            seen.add(v["video_id"])
                            videos.append(v)

        # Step 2: always include a Khan Academy result for academic credibility
        for v in fetch_youtube_videos(f"Khan Academy {gap}", max_results=1):
            if v["video_id"] not in seen:
                seen.add(v["video_id"])
                videos.append(v)

        # Step 3: generic fallback if fewer than 2 videos found
        if len(videos) < 2:
            for v in fetch_youtube_videos(f"{gap} tutorial for beginners", max_results=2):
                if v["video_id"] not in seen:
                    seen.add(v["video_id"])
                    videos.append(v)

        skill_videos[gap] = videos[:3]

    # ── Job listings ───────────────────────────────────
    location   = profile_data.get("location", "Remote") or "Remote"
    role_title = role.get("title", "")
    job_listings = []
    try:
        from adapters.caribbeanjobs import fetch_jobs
        raw_jobs = fetch_jobs(role_title, location=location) or []
        job_listings = [
            {
                "title": job.get("title", role_title),
                "company": job.get("company", "CaribbeanJobs"),
                "location": job.get("location", location),
                "link": job.get("link") or job.get("url") or "",
                "skills": role_top_skills[:3],
                "source": "CaribbeanJobs",
            }
            for job in raw_jobs[:6]
        ]
    except Exception as e:
        print("CaribbeanJobs adapter error:", e)

    if not job_listings:
        encoded_role     = urllib.parse.quote(role_title)
        encoded_location = urllib.parse.quote(location)
        job_listings = [
            {
                "title":    f"{role_title} roles",
                "company":  "LinkedIn Jobs",
                "location": location,
                "link":     f"https://www.linkedin.com/jobs/search/?keywords={encoded_role}&location={encoded_location}",
                "skills":   role_top_skills[:3],
                "source":   "LinkedIn",
            },
            {
                "title":    f"{role_title} openings",
                "company":  "CaribbeanJobs",
                "location": location,
                "link":     f"https://www.caribbeanjobs.com/ShowResults.aspx?Keywords={encoded_role}",
                "skills":   role_top_skills[:3],
                "source":   "CaribbeanJobs",
            },
            {
                "title":    f"{role_title} listings",
                "company":  "Indeed Jamaica",
                "location": location,
                "link":     f"https://jm.indeed.com/jobs?q={encoded_role}&l={encoded_location}",
                "skills":   role_top_skills[:3],
                "source":   "Indeed",
            },
        ]

    # ── Progress checklist ────────────────────────────
    progress = get_progress(
        session.get("user_id"),
        profile_id=session.get("active_profile_id"),
        role_id=selected_role_id,
    )
    if not progress or progress.get("role_id") != selected_role_id:
        progress = {
            "role_id":   selected_role_id,
            "skills":    missing_skills,
            "completed": [],
        }
        progress = save_progress(
            session.get("user_id"),
            progress,
            profile_id=session.get("active_profile_id"),
        )
        session["progress"] = progress
    else:
        progress["skills"] = missing_skills
        progress["completed"] = [
            s for s in progress.get("completed", [])
            if s in missing_skills
        ]
        progress = save_progress(
            session.get("user_id"),
            progress,
            profile_id=session.get("active_profile_id"),
        )
        session["progress"] = progress

    results_obj = {
        "degree":               profile_data.get("degree", ""),
        "location":             profile_data.get("location", ""),
        "optimize_for":         profile_data.get("optimize_for", "balanced"),
        "user_skills":          user_skills,
        "selected_role":        role.get("title", ""),
        "top_skills_in_jobs":   role_top_skills,
        "missing_skills":       missing_skills,
        "scored_gaps":          scored_gaps,
        "match_score":          match_score,
        "recommended_certs":    recommended_certs,
        "recommended_learning": recommended_learning,
        "learning_paths":       learning_paths,
        "skill_videos":         skill_videos,
        "job_listings":         job_listings,
        "unsupported_skills":   unsupported_skills,
        "graph_overview":       build_graph_overview(graph),
    }
    return render_template("results.html", results=results_obj)


@app.route("/progress", methods=["GET", "POST"])
@login_required
def progress():
    profile_id = session.get("active_profile_id")
    selected_role_id = session.get("selected_role_id")
    data = get_progress(
        session.get("user_id"),
        profile_id=profile_id,
        role_id=selected_role_id,
    )
    if not data.get("skills") and session.get("progress"):
        """
    Display and update the user's skill acquisition checklist.

    GET:  Renders progress.html with the current checklist state.
    POST: Saves the submitted completed skills, validates them against
          the allowed skill list (to prevent tampering), and merges newly
          completed skills back into the user's profile so they are
          reflected in future skill gap calculations.

    Session keys read/written:
        progress — dict with role_id, skills (checklist), completed (checked)
        profile  — updated to include newly completed skills
    """
    data = session.get("progress", {"skills": [], "completed": []})

    if request.method == "POST":
        completed = request.form.getlist("completed")
        # keep only items that are still in the checklist
        allowed = set(data.get("skills", []))
        data["completed"] = [c for c in completed if c in allowed]
        if selected_role_id:
            data["role_id"] = selected_role_id
        data = save_progress(session.get("user_id"), data, profile_id=profile_id)
        session["progress"] = data

        # Also merge newly-completed skills into the profile so they
        # persist across sessions and show up in results immediately
        profile = get_latest_profile(session.get("user_id")) or session.get("profile", {})
        if profile:
            existing = {normalize_skill(s) for s in profile.get("skills", [])}
            for s in data["completed"]:
                if normalize_skill(s) not in existing:
                    profile.setdefault("skills", []).append(s)
                    existing.add(normalize_skill(s))
            saved_profile = save_profile(
                session.get("user_id"),
                profile,
                profile_id=profile.get("id") or profile_id,
            )
            if saved_profile:
                profile = saved_profile
                session["active_profile_id"] = saved_profile["id"]
            session["profile"] = profile
        return redirect(url_for("progress"))

    profiles = get_user_profiles(session.get("user_id"))
    return render_template("progress.html", progress=data, profiles=profiles)


@app.route("/survey", methods=["GET"])
@login_required
def survey():
    """
    Generate and display a personalised skill proficiency survey.

    Uses the Groq LLM (llama-3.3-70b-versatile) to generate up to 6
    survey questions tailored to the user's degree, major, and skill gaps.
    Questions use a 1–5 Likert scale. Responses with a score >= 3 are
    treated as confirmed skills in survey_submit.

    If Groq fails or returns invalid JSON, questions defaults to [] and
    the user can skip the survey to proceed directly to results.

    Session keys written:
        survey_gaps — the list of gap skills used to generate questions
    """
    profile_data = get_latest_profile(session.get("user_id")) or session.get("profile")
    if profile_data:
        session["profile"] = profile_data
        session["active_profile_id"] = profile_data.get("id")
    if not profile_data:
        return redirect(url_for("profile"))

    selected_role_id = session.get("selected_role_id")
    role             = find_role_by_id(selected_role_id, load_roles()) if selected_role_id else None
    if not role:
        return redirect(url_for("roles"))

    questions, survey_meta, gaps = build_dynamic_survey_questions(profile_data, role)

    print("Survey claimed role skills:", survey_meta["claimed_target_count"])
    print("Survey gaps found:", gaps)
    print("Survey questions generated:", survey_meta["total"])

    session["survey_gaps"] = gaps
    session["survey_questions"] = questions
    return render_template(
        "survey.html",
        questions=questions,
        survey_meta=survey_meta,
        role=role,
        profile=profile_data,
    )


@app.route("/survey/submit", methods=["POST"])
@login_required
def survey_submit():
    """
    Process survey responses and update the user's confirmed skill list.

    Skills rated 3 or above (out of 5) are added to the user's profile
    skills, making them available for the skill gap calculation in /results.
    Redirects to the loading animation page which then redirects to /results.

    Session keys written:
        profile — updated with newly confirmed skills from the survey
    """
    profile_data = get_latest_profile(session.get("user_id")) or session.get("profile", {})
    survey_scores = []
    for key, score in request.form.items():
        if not key.startswith("score_") or not score.isdigit():
            continue
        index = key.replace("score_", "", 1)
        skill = request.form.get(f"skill_{index}", "").strip()
        reason = request.form.get(f"reason_{index}", "").strip()
        if skill:
            survey_scores.append({
                "skill": skill,
                "reason": reason,
                "score": int(score),
            })

    # Survey answers measure readiness/confidence. They do not mutate
    # confirmed profile skills, because that would erase the skill gap and
    # inflate the match score before the learner completes the roadmap.
    session["survey_scores"] = survey_scores
    session["profile"] = profile_data

    return redirect(url_for("loading"))


@app.route("/set-usertype", methods=["POST"])
def set_usertype():
    """Store the user's account type (student or professional) in the session."""
    session["user_type"] = request.form.get("user_type", "student")
    return redirect(url_for("roles"))


@app.get("/reset")
def reset():
    """
    Clear the user's current pathway data without logging them out.

    Removes profile, selected role, progress, and survey data from the
    session so the user can start a new career pathway from scratch.
    Auth session keys (user_id, display_name) are preserved.
    """
    session.pop("profile", None)
    session.pop("selected_role_id", None)
    session.pop("progress", None)
    session.pop("survey_gaps", None)
    session.pop("survey_scores", None)
    session.pop("survey_questions", None)
    session.pop("flash", None)
    session.pop("resume_notice", None)
    return redirect(url_for("roles"))


@app.get("/loading")
def loading():
    """Render the animated Dijkstra loading screen before /results."""
    return render_template("loading.html")


# ── Firebase session bridge ───────────────────────────────────

@app.post("/set-session")
def set_session():
    """
    Sync Firebase authentication state into the Flask server-side session.

    Called by base.html immediately after every Firebase login event
    (Google OAuth, email/password, or session restoration via
    onAuthStateChanged). Stores user_id and display_name so that
    @login_required decorators and server-side Jinja2 checks work correctly.

    Request body (JSON):
        user_id      (str): Firebase UID
        display_name (str): User's display name or email

    Returns:
        JSON: {"ok": True} on success.
    """
    data = request.get_json(silent=True) or {}
    user = upsert_user(
        data.get("user_id"),
        display_name=data.get("display_name"),
        email=data.get("email"),
        username=data.get("username"),
        user_type=data.get("user_type"),
    )

    display_name = (
        (user or {}).get("display_name")
        or data.get("display_name")
        or data.get("email")
    )

    session["user_id"]      = data.get("user_id")
    session["display_name"] = display_name

    existing_profile = get_latest_profile(data.get("user_id"))
    if existing_profile:
        session["profile"] = existing_profile
        session["active_profile_id"] = existing_profile["id"]

    selected_role_id = session.get("selected_role_id")
    existing_progress = get_progress(
        data.get("user_id"),
        profile_id=session.get("active_profile_id"),
        role_id=selected_role_id,
    )
    if existing_progress.get("skills"):
        session["progress"] = existing_progress

    if user:
        session["db_user_id"] = user["id"]
    return {
        "ok": True,
        "display_name": display_name,
        "email": (user or {}).get("email") or data.get("email"),
    }

@app.get("/logout")
def logout():
    """
    Clear the entire Flask session and redirect to the home page.

    Called when the user clicks Sign Out. Firebase sign-out is handled
    separately on the client side in base.html.
    """
    session.clear()
    return redirect(url_for("home"))


if __name__ == "__main__":
    app.run(debug=True)
