from urllib.parse import quote_plus


def _ms_learn(query):
    return f"https://learn.microsoft.com/en-us/search/?terms={quote_plus(query)}"


skills = [
    "Python", "SQL", "Statistics", "Machine Learning",
    "Data Visualization", "Networking", "Linux",
    "Security Basics", "Cloud", "Git", "APIs", "TensorFlow",
    "Excel", "JavaScript", "Java", "HTML", "CSS",
    "Programming Logic", "Database Fundamentals", "Computer Systems Basics",
    "Command Line Basics", "Math Foundations", "Spreadsheet Basics",
    "Cloud Concepts", "Cloud Platform Basics", "IP Addressing",
    "Relational Data Modeling", "Chart Design Basics", "Security Concepts",
    "HTTP Fundamentals", "Object-Oriented Programming", "Descriptive Statistics Basics"
]

courses = [
    {
        "name": "Programming Logic Foundations",
        "teaches": ["Programming Logic"],
        "prerequisites": [],
        "time": 8,
        "difficulty": 1,
        "cost": 0,
        "provider": "freeCodeCamp",
        "topics": ["Variables", "Conditionals", "Loops", "Problem solving"],
        "ms_learn": _ms_learn("programming logic beginners"),
        "youtube": "https://www.youtube.com/results?search_query=programming+logic+for+beginners"
    },
    {
        "name": "Python for Everybody",
        "teaches": ["Python"],
        "prerequisites": ["Programming Logic"],
        "time": 30,
        "difficulty": 1,
        "cost": 0,
        "provider": "Coursera",
        "topics": ["Syntax and variables", "Control flow", "Functions", "Files and data structures"],
        "ms_learn": _ms_learn("python beginners"),
        "youtube": "https://www.youtube.com/results?search_query=python+for+beginners+full+course"
    },
    {
        "name": "Database Concepts",
        "teaches": ["Database Fundamentals"],
        "prerequisites": [],
        "time": 10,
        "difficulty": 1,
        "cost": 0,
        "provider": "Microsoft Learn",
        "topics": ["Tables", "Keys", "Relationships", "Basic database design"],
        "ms_learn": _ms_learn("database fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=database+fundamentals+for+beginners"
    },
    {
        "name": "Relational Data Modeling",
        "teaches": ["Relational Data Modeling"],
        "prerequisites": ["Database Fundamentals"],
        "time": 12,
        "difficulty": 1,
        "cost": 0,
        "provider": "Microsoft Learn",
        "topics": ["Primary keys", "Foreign keys", "Normalization", "Entity relationships"],
        "ms_learn": _ms_learn("relational database design"),
        "youtube": "https://www.youtube.com/results?search_query=relational+database+design+basics"
    },
    {
        "name": "SQL Fundamentals",
        "teaches": ["SQL"],
        "prerequisites": ["Relational Data Modeling"],
        "time": 20,
        "difficulty": 1,
        "cost": 0,
        "provider": "edX",
        "topics": ["Tables and relationships", "SELECT queries", "Filtering and sorting", "Joins and aggregates"],
        "ms_learn": _ms_learn("SQL fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=sql+fundamentals+full+course"
    },
    {
        "name": "Math Foundations for Data",
        "teaches": ["Math Foundations"],
        "prerequisites": [],
        "time": 12,
        "difficulty": 1,
        "cost": 0,
        "provider": "Khan Academy / Coursera",
        "topics": ["Averages", "Percentages", "Basic probability", "Reading charts"],
        "ms_learn": _ms_learn("math foundations for data science"),
        "youtube": "https://www.youtube.com/results?search_query=math+foundations+for+data+science"
    },
    {
        "name": "Intro to Statistics",
        "teaches": ["Statistics"],
        "prerequisites": ["Descriptive Statistics Basics"],
        "time": 40,
        "difficulty": 2,
        "cost": 0,
        "provider": "edX",
        "topics": ["Descriptive statistics", "Probability", "Distributions", "Hypothesis testing"],
        "ms_learn": _ms_learn("statistics for data science"),
        "youtube": "https://www.youtube.com/results?search_query=statistics+for+data+science+full+course"
    },
    {
        "name": "Descriptive Statistics Basics",
        "teaches": ["Descriptive Statistics Basics"],
        "prerequisites": ["Math Foundations"],
        "time": 10,
        "difficulty": 1,
        "cost": 0,
        "provider": "Khan Academy / Coursera",
        "topics": ["Mean and median", "Variance", "Distributions", "Reading summary tables"],
        "ms_learn": _ms_learn("descriptive statistics basics"),
        "youtube": "https://www.youtube.com/results?search_query=descriptive+statistics+basics"
    },
    {
        "name": "Data Analysis with Python",
        "teaches": ["Data Visualization"],
        "prerequisites": ["Python", "SQL"],
        "time": 40,
        "difficulty": 2,
        "cost": 0,
        "provider": "Coursera",
        "topics": ["Pandas dataframes", "Cleaning datasets", "Exploratory analysis", "Charts and dashboards"],
        "ms_learn": _ms_learn("data visualization with python"),
        "youtube": "https://www.youtube.com/results?search_query=data+analysis+python+pandas+matplotlib+full+course"
    },
    {
        "name": "ML Basics",
        "teaches": ["Machine Learning"],
        "prerequisites": ["Python", "Descriptive Statistics Basics"],
        "time": 60,
        "difficulty": 3,
        "cost": 49,
        "provider": "edX",
        "topics": ["Supervised learning", "Model training", "Evaluation metrics", "Overfitting and validation"],
        "ms_learn": _ms_learn("introduction to machine learning"),
        "youtube": "https://www.youtube.com/results?search_query=machine+learning+full+course+beginners"
    },
    {
        "name": "TensorFlow Fundamentals",
        "teaches": ["TensorFlow"],
        "prerequisites": ["Machine Learning"],
        "time": 50,
        "difficulty": 3,
        "cost": 0,
        "provider": "Google",
        "topics": ["Tensors", "Neural network layers", "Training loops", "Model evaluation"],
        "ms_learn": _ms_learn("tensorflow machine learning"),
        "youtube": "https://www.youtube.com/results?search_query=tensorflow+full+course+beginners"
    },
    {
        "name": "Computer Systems Foundations",
        "teaches": ["Computer Systems Basics"],
        "prerequisites": [],
        "time": 10,
        "difficulty": 1,
        "cost": 0,
        "provider": "Cisco / Microsoft Learn",
        "topics": ["Hardware basics", "Operating systems", "Clients and servers", "Troubleshooting"],
        "ms_learn": _ms_learn("computer systems fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=computer+systems+basics+for+beginners"
    },
    {
        "name": "IP Addressing Basics",
        "teaches": ["IP Addressing"],
        "prerequisites": ["Computer Systems Basics"],
        "time": 12,
        "difficulty": 1,
        "cost": 0,
        "provider": "Cisco NetAcad",
        "topics": ["IPv4 addresses", "Subnets", "Default gateways", "DNS basics"],
        "ms_learn": _ms_learn("IP addressing basics"),
        "youtube": "https://www.youtube.com/results?search_query=ip+addressing+basics"
    },
    {
        "name": "Networking Fundamentals",
        "teaches": ["Networking"],
        "prerequisites": ["IP Addressing"],
        "time": 35,
        "difficulty": 2,
        "cost": 0,
        "provider": "Cisco NetAcad",
        "topics": ["IP addressing", "Routing basics", "Switching basics", "Network troubleshooting"],
        "ms_learn": _ms_learn("networking fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=networking+fundamentals+full+course"
    },
    {
        "name": "Command Line Orientation",
        "teaches": ["Command Line Basics"],
        "prerequisites": ["Computer Systems Basics"],
        "time": 6,
        "difficulty": 1,
        "cost": 0,
        "provider": "Microsoft Learn",
        "topics": ["Terminal basics", "Paths", "Running commands", "Help pages"],
        "ms_learn": _ms_learn("command line basics"),
        "youtube": "https://www.youtube.com/results?search_query=command+line+basics+for+beginners"
    },
    {
        "name": "Linux Command Line Basics",
        "teaches": ["Linux"],
        "prerequisites": ["Command Line Basics"],
        "time": 15,
        "difficulty": 1,
        "cost": 0,
        "provider": "edX",
        "topics": ["Terminal navigation", "Files and directories", "Permissions", "Package management", "Shell basics"],
        "ms_learn": _ms_learn("linux command line basics"),
        "youtube": "https://www.youtube.com/results?search_query=linux+command+line+full+course+beginners"
    },
    {
        "name": "Security Concepts Foundations",
        "teaches": ["Security Concepts"],
        "prerequisites": ["Networking"],
        "time": 18,
        "difficulty": 2,
        "cost": 0,
        "provider": "Microsoft Learn / Cisco",
        "topics": ["CIA triad", "Common threats", "Access control", "Risk basics"],
        "ms_learn": _ms_learn("security concepts fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=security+concepts+for+beginners"
    },
    {
        "name": "CompTIA Security+ Prep",
        "teaches": ["Security Basics"],
        "prerequisites": ["Security Concepts"],
        "time": 60,
        "difficulty": 3,
        "cost": 30,
        "provider": "CompTIA",
        "topics": ["Threats and vulnerabilities", "Identity and access", "Network security", "Incident response"],
        "ms_learn": _ms_learn("security fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=comptia+security+plus+full+course"
    },
    {
        "name": "Cloud Concepts Foundations",
        "teaches": ["Cloud Concepts"],
        "prerequisites": [],
        "time": 8,
        "difficulty": 1,
        "cost": 0,
        "provider": "Microsoft Learn / AWS Skill Builder",
        "topics": ["IaaS, PaaS, and SaaS", "Regions and availability", "Shared responsibility", "Cloud pricing"],
        "ms_learn": _ms_learn("cloud concepts fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=cloud+concepts+for+beginners"
    },
    {
        "name": "Cloud Platform Basics",
        "teaches": ["Cloud Platform Basics"],
        "prerequisites": ["Cloud Concepts"],
        "time": 12,
        "difficulty": 2,
        "cost": 0,
        "provider": "Microsoft Learn / AWS Skill Builder",
        "topics": ["Cloud consoles", "Resource groups", "Virtual machines", "Storage services"],
        "ms_learn": _ms_learn("cloud platform basics"),
        "youtube": "https://www.youtube.com/results?search_query=cloud+platform+basics"
    },
    {
        "name": "AWS Cloud Practitioner",
        "teaches": ["Cloud"],
        "prerequisites": ["Networking"],
        "time": 30,
        "difficulty": 2,
        "cost": 0,
        "provider": "AWS / Microsoft Learn",
        "topics": ["Cloud concepts", "Compute and storage", "Networking in cloud", "Pricing and governance"],
        "ms_learn": _ms_learn("cloud practitioner fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=aws+cloud+practitioner+full+course"
    },
    {
        "name": "Git & GitHub for Beginners",
        "teaches": ["Git"],
        "prerequisites": ["Command Line Basics"],
        "time": 10,
        "difficulty": 1,
        "cost": 0,
        "provider": "GitHub",
        "topics": ["Repositories", "Commits", "Branches", "Pull requests"],
        "ms_learn": _ms_learn("git github fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=git+github+full+course+beginners"
    },
    {
        "name": "HTTP Fundamentals",
        "teaches": ["HTTP Fundamentals"],
        "prerequisites": ["Networking"],
        "time": 10,
        "difficulty": 1,
        "cost": 0,
        "provider": "MDN / Microsoft Learn",
        "topics": ["Requests and responses", "Status codes", "URLs", "Headers"],
        "ms_learn": _ms_learn("HTTP fundamentals web APIs"),
        "youtube": "https://www.youtube.com/results?search_query=http+fundamentals+web+apis"
    },
    {
        "name": "REST API Development",
        "teaches": ["APIs"],
        "prerequisites": ["Python", "HTTP Fundamentals"],
        "time": 25,
        "difficulty": 2,
        "cost": 0,
        "provider": "edX",
        "topics": ["HTTP basics", "Routes and endpoints", "JSON payloads", "Authentication basics"],
        "ms_learn": _ms_learn("REST API development"),
        "youtube": "https://www.youtube.com/results?search_query=rest+api+development+python+full+course"
    },
    {
        "name": "HTML Foundations",
        "teaches": ["HTML"],
        "prerequisites": [],
        "time": 10,
        "difficulty": 1,
        "cost": 0,
        "provider": "MDN / freeCodeCamp",
        "topics": ["HTML structure", "Semantic elements", "Forms", "Page content"],
        "ms_learn": _ms_learn("HTML fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=html+css+full+course+beginners"
    },
    {
        "name": "CSS Layout Fundamentals",
        "teaches": ["CSS"],
        "prerequisites": ["HTML"],
        "time": 12,
        "difficulty": 1,
        "cost": 0,
        "provider": "MDN / freeCodeCamp",
        "topics": ["Selectors", "Box model", "Flexbox", "Responsive layout"],
        "ms_learn": _ms_learn("CSS layout fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=css+layout+fundamentals"
    },
    {
        "name": "JavaScript Basics",
        "teaches": ["JavaScript"],
        "prerequisites": ["CSS"],
        "time": 30,
        "difficulty": 2,
        "cost": 0,
        "provider": "freeCodeCamp",
        "topics": ["Variables and functions", "DOM manipulation", "Events", "Fetch and async basics"],
        "ms_learn": _ms_learn("JavaScript basics"),
        "youtube": "https://www.youtube.com/results?search_query=javascript+full+course+beginners"
    },
    {
        "name": "Java Programming Fundamentals",
        "teaches": ["Java"],
        "prerequisites": ["Object-Oriented Programming"],
        "time": 40,
        "difficulty": 2,
        "cost": 0,
        "provider": "edX",
        "topics": ["Classes and objects", "Control flow", "Collections", "Error handling"],
        "ms_learn": _ms_learn("Java programming fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=java+programming+full+course+beginners"
    },
    {
        "name": "Object-Oriented Programming Basics",
        "teaches": ["Object-Oriented Programming"],
        "prerequisites": ["Programming Logic"],
        "time": 12,
        "difficulty": 2,
        "cost": 0,
        "provider": "Microsoft Learn / edX",
        "topics": ["Classes", "Objects", "Methods", "Encapsulation"],
        "ms_learn": _ms_learn("object oriented programming basics"),
        "youtube": "https://www.youtube.com/results?search_query=object+oriented+programming+basics"
    },
    {
        "name": "Statistics for Data Science",
        "teaches": ["Statistics"],
        "prerequisites": ["Descriptive Statistics Basics"],
        "time": 35,
        "difficulty": 2,
        "cost": 0,
        "provider": "Coursera",
        "topics": ["Descriptive statistics", "Probability", "Sampling", "Statistical inference"],
        "ms_learn": _ms_learn("statistics for data science"),
        "youtube": "https://www.youtube.com/results?search_query=statistics+for+data+science+beginners"
    },
    {
        "name": "Spreadsheet Basics",
        "teaches": ["Spreadsheet Basics"],
        "prerequisites": [],
        "time": 6,
        "difficulty": 1,
        "cost": 0,
        "provider": "Microsoft Learn",
        "topics": ["Cells", "Formulas", "Formatting", "Simple charts"],
        "ms_learn": _ms_learn("spreadsheet basics"),
        "youtube": "https://www.youtube.com/results?search_query=spreadsheet+basics+for+beginners"
    },
    {
        "name": "Excel Foundations",
        "teaches": ["Excel"],
        "prerequisites": ["Spreadsheet Basics"],
        "time": 12,
        "difficulty": 1,
        "cost": 0,
        "provider": "Microsoft Learn",
        "topics": ["Formulas", "Tables", "Charts", "Basic analysis"],
        "ms_learn": _ms_learn("Excel fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=excel+fundamentals+course"
    },
    {
        "name": "Chart Design Principles",
        "teaches": ["Chart Design Basics"],
        "prerequisites": ["Excel"],
        "time": 10,
        "difficulty": 1,
        "cost": 0,
        "provider": "Microsoft Learn / Tableau",
        "topics": ["Choosing chart types", "Axes and labels", "Color use", "Storytelling with charts"],
        "ms_learn": _ms_learn("data visualization chart design"),
        "youtube": "https://www.youtube.com/results?search_query=chart+design+data+visualization+basics"
    },
    {
        "name": "Cloud Automation Fast Track",
        "teaches": ["Cloud"],
        "prerequisites": ["Cloud Platform Basics"],
        "time": 15,
        "difficulty": 3,
        "cost": 45,
        "provider": "Cloud Bootcamp",
        "topics": ["Cloud consoles", "Resource groups", "Deployments", "CLI tools"],
        "ms_learn": _ms_learn("cloud automation fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=cloud+automation+python+course"
    },
    {
        "name": "Linux to Cloud Foundations",
        "teaches": ["Cloud"],
        "prerequisites": ["Linux"],
        "time": 55,
        "difficulty": 1,
        "cost": 0,
        "provider": "Microsoft Learn / Linux Foundation",
        "topics": ["Linux servers", "Cloud hosting", "VMs", "Cloud administration"],
        "ms_learn": _ms_learn("linux cloud fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=linux+cloud+fundamentals"
    },
    {
        "name": "Applied Machine Learning Bootcamp",
        "teaches": ["Machine Learning"],
        "prerequisites": ["Python", "Descriptive Statistics Basics"],
        "time": 25,
        "difficulty": 3,
        "cost": 150,
        "provider": "Bootcamp",
        "topics": ["Supervised learning", "Model training", "Evaluation", "Applied ML projects"],
        "ms_learn": _ms_learn("applied machine learning"),
        "youtube": "https://www.youtube.com/results?search_query=applied+machine+learning+python+bootcamp"
    },
    {
        "name": "Linux Security Foundations",
        "teaches": ["Security Basics"],
        "prerequisites": ["Linux", "Security Concepts"],
        "time": 80,
        "difficulty": 1,
        "cost": 0,
        "provider": "Linux Foundation",
        "topics": ["Linux permissions", "User access", "Firewalls", "Security hardening"],
        "ms_learn": _ms_learn("linux security basics"),
        "youtube": "https://www.youtube.com/results?search_query=linux+security+basics"
    },
    {
        "name": "Cybersecurity Fast Track",
        "teaches": ["Security Basics"],
        "prerequisites": ["Cloud", "Security Concepts"],
        "time": 20,
        "difficulty": 3,
        "cost": 80,
        "provider": "Cybersecurity Bootcamp",
        "topics": ["Threats", "IAM", "Cloud security", "Incident response"],
        "ms_learn": _ms_learn("cybersecurity fundamentals"),
        "youtube": "https://www.youtube.com/results?search_query=cybersecurity+fast+track"
    },
    {
        "name": "SQL Dashboard Studio",
        "teaches": ["Data Visualization"],
        "prerequisites": ["SQL"],
        "time": 10,
        "difficulty": 3,
        "cost": 35,
        "provider": "Tableau / Power BI Lab",
        "topics": ["SQL summaries", "Dashboard layout", "Charts", "Stakeholder reporting"],
        "ms_learn": _ms_learn("SQL dashboard data visualization"),
        "youtube": "https://www.youtube.com/results?search_query=sql+dashboard+data+visualization+course"
    },
    {
        "name": "Excel Dashboard Essentials",
        "teaches": ["Data Visualization"],
        "prerequisites": ["Chart Design Basics"],
        "time": 45,
        "difficulty": 1,
        "cost": 0,
        "provider": "Microsoft Learn",
        "topics": ["Pivot charts", "Conditional formatting", "Dashboards", "Storytelling"],
        "ms_learn": _ms_learn("Excel dashboard visualization"),
        "youtube": "https://www.youtube.com/results?search_query=excel+dashboard+data+visualization"
    },
    {
        "name": "JavaScript API Client Projects",
        "teaches": ["APIs"],
        "prerequisites": ["JavaScript", "HTTP Fundamentals"],
        "time": 18,
        "difficulty": 2,
        "cost": 0,
        "provider": "freeCodeCamp",
        "topics": ["Fetch", "JSON", "Async requests", "API authentication"],
        "ms_learn": _ms_learn("JavaScript API fetch"),
        "youtube": "https://www.youtube.com/results?search_query=javascript+api+fetch+course"
    },
    {
        "name": "Java API Services",
        "teaches": ["APIs"],
        "prerequisites": ["Java", "HTTP Fundamentals"],
        "time": 35,
        "difficulty": 3,
        "cost": 40,
        "provider": "edX",
        "topics": ["REST services", "Controllers", "JSON responses", "Service testing"],
        "ms_learn": _ms_learn("Java REST API"),
        "youtube": "https://www.youtube.com/results?search_query=java+rest+api+course"
    },
    {
        "name": "API Quickstart with GitHub Tools",
        "teaches": ["APIs"],
        "prerequisites": ["Git", "HTTP Fundamentals"],
        "time": 12,
        "difficulty": 2,
        "cost": 35,
        "provider": "Developer Bootcamp",
        "topics": ["API clients", "GitHub API", "Tokens", "Request testing"],
        "ms_learn": _ms_learn("API quickstart GitHub"),
        "youtube": "https://www.youtube.com/results?search_query=api+quickstart+github+tools"
    },
    {
        "name": "SQL API Integration Basics",
        "teaches": ["APIs"],
        "prerequisites": ["SQL", "HTTP Fundamentals"],
        "time": 40,
        "difficulty": 1,
        "cost": 0,
        "provider": "edX",
        "topics": ["Data endpoints", "Query parameters", "JSON data", "API-backed reports"],
        "ms_learn": _ms_learn("SQL API integration"),
        "youtube": "https://www.youtube.com/results?search_query=sql+api+integration+basics"
    },
    {
        "name": "TensorFlow Fast Track",
        "teaches": ["TensorFlow"],
        "prerequisites": ["Machine Learning"],
        "time": 28,
        "difficulty": 4,
        "cost": 120,
        "provider": "Deep Learning Bootcamp",
        "topics": ["Tensors", "Keras models", "Training loops", "Deployment"],
        "ms_learn": _ms_learn("TensorFlow Python"),
        "youtube": "https://www.youtube.com/results?search_query=tensorflow+python+fast+track"
    },
    {
        "name": "Cloud ML Deployment",
        "teaches": ["TensorFlow"],
        "prerequisites": ["Cloud", "Machine Learning"],
        "time": 45,
        "difficulty": 2,
        "cost": 0,
        "provider": "Google Cloud Skills Boost",
        "topics": ["Model hosting", "Cloud notebooks", "Inference endpoints", "Monitoring"],
        "ms_learn": _ms_learn("cloud machine learning deployment"),
        "youtube": "https://www.youtube.com/results?search_query=cloud+machine+learning+deployment+course"
    },
]
